---
arista1:
  hostname: arista1.lasthop.io
  data:
    role: WAN
    site_details:
      wifi_password: verysupersecure
  port: 8443
  groups:
    - eos
    - sfo

arista2:
  hostname: arista2.lasthop.io
  data:
    role: WAN
    site_details:
      wifi_password: racecar
  port: 22
  groups:
    - eos
    - sea

arista3:
  hostname: arista3.lasthop.io
  data:
    role: AGG
  port: 8443
  groups:
    - sea
    - eos
