---
cisco3:
    hostname: cisco3.lasthop.io
    groups:
      - ios

cisco4:
    hostname: cisco4.lasthop.io
    groups:
      - ios

nxos1:
    hostname: nxos1.lasthop.io
    groups:
      - nxos
    data:
      interfaces:
        - int_name: Eth1/4
          ip_address: 172.31.100.1
          subnet_mask: 255.255.255.252 
        - int_name: Lo101
          ip_address: 172.31.101.101
          subnet_mask: 255.255.255.255
        - int_name: Lo102
          ip_address: 172.31.102.101
          subnet_mask: 255.255.255.255
      bgp:
        asn: 22
        router_id: 172.31.101.101
        ipv4_unicast_prefixes:
          - {ip: 172.31.101.101, route_mask: 32}
          - {ip: 172.31.102.101, route_mask: 32}
        neighbors:
          - remote_peer: 172.31.100.2
            remote_asn: 22
            route_maps:
              - direction: out
                name: NXOS2_Peer
      bgp_prefix_lists:
        - Loopback101:
          - seq_num: 5
            action: permit
            prefix: 172.31.101.101/32
      bgp_route_maps:
        - NXOS2_Peer:
          - seq_num: 100 
            action: permit
            match: Loopback101
        
nxos2:
    hostname: nxos2.lasthop.io
    groups:
      - nxos
    data:
      interfaces:
        - int_name: Eth1/4
          ip_address: 172.31.100.2
          subnet_mask: 255.255.255.252 
        - int_name: Lo101
          ip_address: 172.31.101.102
          subnet_mask: 255.255.255.255
        - int_name: Lo102
          ip_address: 172.31.102.102
          subnet_mask: 255.255.255.255
      bgp:
        asn: 22
        router_id: 172.31.101.102
        ipv4_unicast_prefixes:
          - {ip: 172.31.101.102, route_mask: 32}
          - {ip: 172.31.102.102, route_mask: 32}
        neighbors:
          - remote_peer: 172.31.100.1
            remote_asn: 22
            route_maps:
              - direction: out
                name: NXOS1_Peer
      bgp_prefix_lists:
        - Loopback101:
          - seq_num: 5
            action: permit
            prefix: 172.31.101.102/32
      bgp_route_maps:
        - NXOS1_Peer:
          - seq_num: 100 
            action: permit
            match: Loopback101

arista1:
    hostname: arista1.lasthop.io
    groups:
      - eos

arista2:
    hostname: arista2.lasthop.io
    groups:
      - eos

arista3:
    hostname: arista3.lasthop.io
    groups:
      - eos

arista4:
    hostname: arista4.lasthop.io
    groups:
      - eos

srx2:
    hostname: srx2.lasthop.io
    groups:
      - junos
